-- Conventions
--   * ids are uuid generated by the app (UUIDv7) so they are known before encryption
--   * every user-owned table has owner_id/user_id NOT NULL + an index that starts with it
--   * *_enc columns hold AES-256-GCM envelopes (v1.<keyId>.<iv>.<tag>.<ct>), never plaintext
--   * *_bidx columns hold HMAC-SHA256 blind indexes for equality lookups on encrypted data
--   * secrets that are only ever compared (passwords, OTPs, recovery codes, session tokens) are hashed, not encrypted

CREATE TABLE users (
  id            uuid PRIMARY KEY,
  email_enc     text NOT NULL,                 -- AAD: users / email_enc / id / id
  email_bidx    text NOT NULL UNIQUE,          -- blindIndex('users.email', normalizeEmail(email))
  password_hash text NOT NULL,                 -- argon2id
  role          text NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sessions (
  token_hash   bytea PRIMARY KEY,              -- sha256(raw cookie token)
  user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  mfa_verified boolean NOT NULL DEFAULT false, -- false = mfa_pending session (short expiry)
  expires_at   timestamptz NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX sessions_user_idx ON sessions (user_id);

CREATE TABLE mfa_totp (
  user_id      uuid PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  secret_enc   text NOT NULL,                  -- AAD: mfa_totp / secret_enc / user_id / user_id
  confirmed_at timestamptz,
  last_step    bigint                          -- replay guard: reject steps <= last_step
);

CREATE TABLE mfa_email_otp (
  id          uuid PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash   text NOT NULL,                   -- HMAC-SHA256 with OTP_PEPPER
  attempts    int  NOT NULL DEFAULT 0,
  expires_at  timestamptz NOT NULL,
  consumed_at timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX mfa_email_otp_user_idx ON mfa_email_otp (user_id, created_at DESC);

CREATE TABLE mfa_recovery_codes (
  id        uuid PRIMARY KEY,
  user_id   uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code_hash text NOT NULL,                     -- HMAC-SHA256 with OTP_PEPPER; plaintext shown once
  used_at   timestamptz
);
CREATE INDEX mfa_recovery_codes_user_idx ON mfa_recovery_codes (user_id);

-- Example user-owned resource
CREATE TABLE notes (
  id         uuid PRIMARY KEY,
  owner_id   uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title      text NOT NULL,
  body_enc   text NOT NULL,                    -- AAD: notes / body_enc / id / owner_id
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX notes_owner_idx ON notes (owner_id, created_at DESC);

-- Optional defence in depth: Postgres row-level security.
-- Only enable it once the app sets the actor in every transaction:
--   BEGIN; SELECT set_config('app.user_id', $1, true); ...; COMMIT;
-- and connects as a role that does not own the table (owners bypass RLS unless FORCE is set).
--
-- ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE notes FORCE ROW LEVEL SECURITY;
-- CREATE POLICY notes_owner ON notes
--   USING (owner_id = current_setting('app.user_id', true)::uuid)
--   WITH CHECK (owner_id = current_setting('app.user_id', true)::uuid);
